"use client";

import { useCallback, useEffect, useState } from "react";
import type { FocusSession, Project, Task, WorkspaceData } from "../../types/workspace";
import { humanDate } from "../../utils/dates";
import { recordFocusSession } from "../../utils/domain";

interface ActiveFocus { duration: number; secondsLeft: number; taskId: string | null; projectId: string | null; startedAt: string; paused: boolean; }

export function FocusView({ data, initialTaskId, onRecord, onCapture, onActiveChange }: { data: WorkspaceData; initialTaskId?: string | null; onRecord: (session: FocusSession) => void; onCapture: (content: string) => void; onActiveChange: (active: boolean) => void }) {
  const initialTask = data.tasks.find((item) => item.id === initialTaskId);
  const [duration, setDuration] = useState(data.preferences.defaultFocusMinutes); const [taskId, setTaskId] = useState(initialTaskId ?? ""); const [projectId, setProjectId] = useState(initialTask?.projectId ?? ""); const [custom, setCustom] = useState(""); const [active, setActive] = useState<ActiveFocus | null>(null); const [thought, setThought] = useState("");
  useEffect(() => { onActiveChange(!!active); return () => onActiveChange(false); }, [active, onActiveChange]);
  const start = () => { const chosen = custom ? Math.max(1, Math.min(180, Number(custom))) : duration; setActive({ duration: chosen, secondsLeft: chosen * 60, taskId: taskId || null, projectId: projectId || null, startedAt: new Date().toISOString(), paused: false }); };
  const finish = useCallback((outcome: "FINISHED" | "CANCELLED") => { if (!active) return; const elapsedSeconds = active.duration * 60 - active.secondsLeft; onRecord(recordFocusSession({ durationMinutes: active.duration, elapsedSeconds, taskId: active.taskId, projectId: active.projectId, startedAt: active.startedAt, outcome })); setActive(null); }, [active, onRecord]);
  useEffect(() => { if (!active || active.paused || active.secondsLeft <= 0) return; const timer = window.setInterval(() => setActive((current) => current ? { ...current, secondsLeft: Math.max(0, current.secondsLeft - 1) } : null), 1000); return () => clearInterval(timer); }, [active]);
  useEffect(() => { if (active?.secondsLeft !== 0) return; const timer = window.setTimeout(() => finish("FINISHED"), 0); return () => clearTimeout(timer); }, [active?.secondsLeft, finish]);
  const time = active ? `${Math.floor(active.secondsLeft / 60).toString().padStart(2, "0")}:${(active.secondsLeft % 60).toString().padStart(2, "0")}` : "";
  const linkedTask = active && data.tasks.find((item) => item.id === active.taskId); const linkedProject = active && data.projects.find((item) => item.id === active.projectId);
  if (active) return <div className="focus-active"><div className="focus-orbit"><span>{time}</span></div><div className="focus-subject"><small>Focusing on</small><h1>{linkedTask?.title ?? linkedProject?.name ?? "Open focus"}</h1></div><div className="focus-controls"><button className="button primary" onClick={() => setActive({ ...active, paused: !active.paused })}>{active.paused ? "Resume" : "Pause"}</button><button className="button quiet" onClick={() => finish("FINISHED")}>Finish</button><button className="button danger-quiet" onClick={() => finish("CANCELLED")}>Cancel</button></div><div className="focus-capture"><input value={thought} onChange={(event) => setThought(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && thought.trim()) { onCapture(thought.trim()); setThought(""); } }} placeholder="Save a thought without leaving focus…" /><button onClick={() => { if (thought.trim()) { onCapture(thought.trim()); setThought(""); } }}>Save thought</button></div></div>;
  return <div className="view focus-view"><header className="view-header"><div><p className="eyebrow">One thing at a time</p><h1>Focus</h1></div></header><section className="focus-setup"><div className="duration-picker"><h2>Choose a duration</h2><div>{[15,25,45,60,90].map((item) => <button className={duration === item && !custom ? "active" : ""} onClick={() => { setDuration(item); setCustom(""); }} key={item}>{item}<small>min</small></button>)}<label className={custom ? "active" : ""}><input type="number" min="1" max="180" value={custom} onChange={(event) => setCustom(event.target.value)} placeholder="—" /><small>custom</small></label></div></div><div className="focus-attach"><label>Task<select value={taskId} onChange={(event) => { const value = event.target.value; setTaskId(value); const task = data.tasks.find((item) => item.id === value); if (task?.projectId) setProjectId(task.projectId); }}><option value="">No task</option>{data.tasks.filter((task) => task.status === "OPEN").map((task) => <option value={task.id} key={task.id}>{task.title}</option>)}</select></label><label>Project<select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">No project</option>{data.projects.filter((project) => project.status === "ACTIVE").map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label></div><button className="button primary focus-start" onClick={start}>Start focus</button></section><FocusHistory sessions={data.focusSessions} tasks={data.tasks} projects={data.projects} /></div>;
}

function FocusHistory({ sessions, tasks, projects }: { sessions: FocusSession[]; tasks: Task[]; projects: Project[] }) {
  return <section className="focus-history"><div className="section-heading"><h2>History</h2><span>{sessions.length} sessions</span></div>{sessions.length ? <div className="history-list">{sessions.map((session) => { const task = tasks.find((item) => item.id === session.taskId); const project = projects.find((item) => item.id === session.projectId); return <div key={session.id}><span className={`history-state ${session.outcome.toLowerCase()}`}>{session.outcome === "FINISHED" ? "✓" : "×"}</span><div><b>{task?.title ?? project?.name ?? "Open focus"}</b><small>{humanDate(session.startedAt.slice(0, 10))} · {Math.round(session.elapsedSeconds / 60)} min</small></div><span>{session.outcome === "FINISHED" ? "Finished" : "Cancelled"}</span></div>; })}</div> : <div className="empty-state"><h2>No Focus sessions yet.</h2><p>Completed sessions will be recorded here.</p></div>}</section>;
}
