"use client";

import { useEffect, useMemo, useState } from "react";
import type { Note, Project } from "../../types/workspace";

const renderMarkdown = (content: string) => content.split("\n").map((line, index) => {
  if (line.startsWith("# ")) return <h1 key={index}>{line.slice(2)}</h1>;
  if (line.startsWith("## ")) return <h2 key={index}>{line.slice(3)}</h2>;
  if (line.startsWith("- ")) return <li key={index}>{line.slice(2)}</li>;
  return line ? <p key={index}>{line}</p> : <br key={index} />;
});

export function NotesView({ notes, projects, initialId, saveState, onAdd, onCreated, onUpdate, onDelete }: { notes: Note[]; projects: Project[]; initialId?: string; saveState: "saved" | "error"; onAdd: () => string; onCreated: (id: string) => void; onUpdate: (id: string, patch: Partial<Note>) => void; onDelete: (note: Note) => void }) {
  const [selectedId, setSelectedId] = useState(initialId ?? notes[0]?.id ?? ""); const [query, setQuery] = useState(""); const [preview, setPreview] = useState(false); const selected = notes.find((note) => note.id === selectedId);
  const [draft, setDraft] = useState(selected ?? null);
  useEffect(() => { if (!draft || !selected || (draft.title === selected.title && draft.content === selected.content && draft.projectId === selected.projectId)) return; const timer = window.setTimeout(() => onUpdate(draft.id, { title: draft.title, content: draft.content, projectId: draft.projectId }), 450); return () => clearTimeout(timer); }, [draft, selected, onUpdate]);
  const filtered = useMemo(() => [...notes].filter((note) => `${note.title} ${note.content}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => Number(b.isPinned) - Number(a.isPinned) || b.updatedAt.localeCompare(a.updatedAt)), [notes, query]);
  const create = () => { const noteId = onAdd(); onCreated(noteId); };
  return <div className="notes-workspace"><aside className="notes-sidebar"><header><div><h1>Notes</h1><span>{notes.length}</span></div><button className="icon-button filled" onClick={create} aria-label="New note">＋</button></header><input className="notes-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search notes" aria-label="Search notes" /><div className="notes-list">{filtered.map((note) => <button className={note.id === selectedId ? "active" : ""} onClick={() => { setSelectedId(note.id); setDraft(note); }} key={note.id}><span>{note.isPinned && "◆ "}{note.title || "Untitled note"}</span><small>{note.content.replace(/[#*\n]/g, " ").slice(0, 72) || "Empty note"}</small></button>)}{!filtered.length && <div className="notes-empty">Start your first note.</div>}</div></aside>
    {draft ? <section className="note-editor"><header><div className="note-status"><button className="mobile-notes-back" onClick={() => { setSelectedId(""); setDraft(null); }}>← Notes</button><span className={saveState === "saved" ? "saved" : "save-error"}>{saveState === "saved" ? "Saved" : "Not saved"}</span></div><div><button className={preview ? "" : "active"} onClick={() => setPreview(false)}>Edit</button><button className={preview ? "active" : ""} onClick={() => setPreview(true)}>Preview</button><button className={`icon-button ${draft.isPinned ? "active" : ""}`} onClick={() => { onUpdate(draft.id, { isPinned: !draft.isPinned }); setDraft({ ...draft, isPinned: !draft.isPinned }); }} aria-label={draft.isPinned ? "Unpin note" : "Pin note"}>◆</button><button className={`icon-button ${draft.isFavorite ? "active" : ""}`} onClick={() => { onUpdate(draft.id, { isFavorite: !draft.isFavorite }); setDraft({ ...draft, isFavorite: !draft.isFavorite }); }} aria-label={draft.isFavorite ? "Remove favorite" : "Favorite note"}>☆</button><button className="icon-button" onClick={() => onDelete(draft)} aria-label="Delete note">⌫</button></div></header>{preview ? <article className="markdown-preview">{renderMarkdown(draft.content)}</article> : <div className="writing-surface"><input className="note-title-input" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Untitled note" /><div className="note-tools"><select value={draft.projectId ?? ""} onChange={(event) => setDraft({ ...draft, projectId: event.target.value || null })}><option value="">No project</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select><span>Markdown supported</span></div><textarea value={draft.content} onChange={(event) => setDraft({ ...draft, content: event.target.value })} placeholder="Start writing…" aria-label="Note content" /></div>}</section> : <section className="note-editor empty-state large"><h2>Start your first note.</h2><p>Keep decisions, checklists, and project details close to the work.</p><button className="button primary" onClick={create}>New note</button></section>}
  </div>;
}
