"use client";

import { useState } from "react";
import type { Note, Project, Task, WorkspaceData } from "../../types/workspace";
import { humanDate } from "../../utils/dates";
import { projectProgress } from "../../utils/domain";
import { TaskRow } from "../../components/TaskRow";

export function ProjectsView({ data, onOpen, onAdd }: { data: WorkspaceData; onOpen: (id: string) => void; onAdd: (name: string) => void }) {
  const [adding, setAdding] = useState(false); const [name, setName] = useState("");
  const active = data.projects.filter((project) => project.status !== "ARCHIVED");
  return <div className="view wide-view"><header className="view-header"><div><p className="eyebrow">Work with a clear finish line</p><h1>Projects</h1></div><button className="button primary" onClick={() => setAdding(true)}>＋ New project</button></header>{adding && <form className="inline-create" onSubmit={(event) => { event.preventDefault(); if (name.trim()) { onAdd(name.trim()); setName(""); setAdding(false); } }}><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Project name" aria-label="Project name" /><button className="button primary">Create</button><button type="button" className="button quiet" onClick={() => setAdding(false)}>Cancel</button></form>}
    {active.length ? <div className="project-table"><div className="project-table-head"><span>Project</span><span>Next action</span><span>Deadline</span><span>Progress</span></div>{active.map((project) => { const progress = projectProgress(project.id, data.tasks); const next = data.tasks.filter((task) => task.projectId === project.id && task.status === "OPEN").sort((a, b) => a.sortOrder - b.sortOrder)[0]; return <button className="project-line" onClick={() => onOpen(project.id)} key={project.id}><span className="project-name"><i style={{ background: project.accent }} /> <b>{project.name}</b><small>{project.status.toLowerCase()}</small></span><span>{next?.title ?? "No next action"}</span><span className={project.deadline && project.deadline < new Date().toISOString().slice(0, 10) ? "overdue" : ""}>{humanDate(project.deadline)}</span><span className="progress-cell"><span className="progress-track"><i style={{ width: `${progress.percent}%` }} /></span><small>{progress.completed}/{progress.total}</small></span></button>; })}</div> : <div className="empty-state large"><h2>No active projects.</h2><p>Create a project when a piece of work needs more than one step.</p><button className="button primary" onClick={() => setAdding(true)}>New project</button></div>}
  </div>;
}

export function ProjectDetail({ project, data, onBack, onUpdate, onToggle, onEditTask, onAddTask, onOpenNote }: { project: Project; data: WorkspaceData; onBack: () => void; onUpdate: (patch: Partial<Project>) => void; onToggle: (task: Task) => void; onEditTask: (task: Task) => void; onAddTask: () => void; onOpenNote: (note: Note) => void }) {
  const [tab, setTab] = useState<"overview" | "tasks" | "notes" | "activity">("overview"); const [editing, setEditing] = useState(false); const [description, setDescription] = useState(project.description);
  const tasks = data.tasks.filter((task) => task.projectId === project.id); const notes = data.notes.filter((note) => note.projectId === project.id); const progress = projectProgress(project.id, tasks); const next = tasks.find((task) => task.status === "OPEN"); const activity = data.activities.filter((item) => item.projectId === project.id);
  return <div className="view wide-view project-detail"><button className="back-link" onClick={onBack}>← Projects</button><header className="project-hero"><div><span className="project-status"><i style={{ background: project.accent }} />{project.status.toLowerCase()}</span><h1>{project.name}</h1></div><select value={project.status} onChange={(event) => onUpdate({ status: event.target.value as Project["status"] })} aria-label="Project status"><option value="ACTIVE">Active</option><option value="PAUSED">Paused</option><option value="COMPLETED">Completed</option><option value="ARCHIVED">Archived</option></select></header><div className="tabs">{(["overview", "tasks", "notes", "activity"] as const).map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    {tab === "overview" && <div className="project-overview"><section><div className="section-heading"><h2>About</h2><button className="text-button" onClick={() => setEditing(!editing)}>{editing ? "Cancel" : "Edit"}</button></div>{editing ? <div className="description-edit"><textarea value={description} onChange={(event) => setDescription(event.target.value)} /><button className="button primary" onClick={() => { onUpdate({ description }); setEditing(false); }}>Save</button></div> : <p>{project.description || "Add a short description for this project."}</p>}</section><aside><div><span>Deadline</span><input type="date" value={project.deadline ?? ""} onChange={(event) => onUpdate({ deadline: event.target.value || null })} /></div><div><span>Progress</span><b>{progress.percent}%</b><div className="progress-track large"><i style={{ width: `${progress.percent}%` }} /></div><small>{progress.remaining} remaining</small></div><div><span>Next action</span><b>{next?.title ?? "No open tasks"}</b></div></aside></div>}
    {tab === "tasks" && <section className="detail-section"><div className="section-heading"><h2>Project tasks</h2><button className="button primary small" onClick={onAddTask}>＋ Add task</button></div><div className="task-list full">{tasks.length ? tasks.map((task) => <TaskRow key={task.id} task={task} projects={data.projects} onToggle={() => onToggle(task)} onEdit={() => onEditTask(task)} />) : <div className="inline-empty"><p>No tasks in this project.</p><button onClick={onAddTask}>Add the first task</button></div>}</div></section>}
    {tab === "notes" && <section className="detail-section"><div className="section-heading"><h2>Linked notes</h2></div>{notes.length ? <div className="linked-notes">{notes.map((note) => <button key={note.id} onClick={() => onOpenNote(note)}><b>{note.title}</b><span>{note.content.replace(/[#*\n]/g, " ").slice(0, 100)}</span></button>)}</div> : <div className="inline-empty"><p>No notes linked to this project.</p></div>}</section>}
    {tab === "activity" && <section className="detail-section"><h2>Activity</h2>{activity.length ? <div className="activity-list">{activity.map((item) => <div key={item.id}><i /><p>{item.text}<span>{humanDate(item.createdAt.slice(0, 10))}</span></p></div>)}</div> : <div className="inline-empty"><p>Activity will appear as you complete tasks, create notes, and change deadlines.</p></div>}</section>}
  </div>;
}
