"use client";

import { useState, type ReactNode } from "react";
type ViewName = string;
export function AppShell({ view, focusActive, name, inboxCount, children, onNavigate, onQuickAdd, onSearch }: { view: ViewName; focusActive: boolean; name: string; inboxCount: number; children: ReactNode; onNavigate: (view: string) => void; onQuickAdd: () => void; onSearch: () => void }) {
  const [moreOpen, setMoreOpen] = useState(false);
  const nav = [{ id:"today", label:"Today", icon:"○" },{ id:"tasks", label:"Tasks", icon:"✓" },{ id:"projects", label:"Projects", icon:"◇" },{ id:"notes", label:"Notes", icon:"▤" },{ id:"focus", label:"Focus", icon:"◉" }];
  const base = view.split(":")[0].split("-")[0];
  const go = (target: string) => { setMoreOpen(false); onNavigate(target); };
  return <main className={`app-shell ${focusActive ? "focus-running" : ""}`}><aside className="app-sidebar"><button className="brand" onClick={() => onNavigate("today")}><span className="brand-mark" />Orbit Desk</button><button className="quick-add" onClick={onQuickAdd}><span>＋</span> Quick add <kbd>Q</kbd></button><nav aria-label="Workspace"><p>Workspace</p>{nav.map((item) => <button className={base === item.id ? "active" : ""} onClick={() => onNavigate(item.id)} key={item.id}><span className="nav-icon">{item.icon}</span>{item.label}</button>)}<p>Organize</p><button className={base === "inbox" ? "active" : ""} onClick={() => onNavigate("inbox")}><span className="nav-icon">⌑</span>Inbox{inboxCount > 0 && <small>{inboxCount}</small>}</button><button onClick={onSearch}><span className="nav-icon">⌕</span>Search<kbd>⌘K</kbd></button><button className={base === "review" ? "active" : ""} onClick={() => onNavigate("review")}><span className="nav-icon">↻</span>Weekly Review</button></nav><button className={`profile-button ${base === "settings" ? "active" : ""}`} onClick={() => onNavigate("settings")}><span>{name ? name.split(/\s+/).map((part) => part[0]).join("").slice(0,2).toUpperCase() : "OD"}</span><b>{name || "Orbit Desk"}<small>Settings</small></b><i>···</i></button></aside><section className="app-content">{children}</section>{moreOpen && <div className="mobile-more-menu" role="dialog" aria-label="More workspace views"><div><b>Workspace</b><button onClick={() => go("projects")}>◇ Projects</button><button onClick={() => go("notes")}>▤ Notes</button><button onClick={() => go("inbox")}>⌑ Inbox <span>{inboxCount || ""}</span></button><button onClick={() => go("review")}>↻ Weekly Review</button><button onClick={onSearch}>⌕ Search</button><button onClick={() => go("settings")}>⚙ Settings</button></div><button className="more-scrim" onClick={() => setMoreOpen(false)} aria-label="Close more menu" /></div>}<nav className="mobile-nav" aria-label="Mobile navigation">{nav.slice(0,2).map((item) => <button className={base === item.id ? "active" : ""} onClick={() => go(item.id)} key={item.id}><span>{item.icon}</span>{item.label}</button>)}<button className="mobile-add" onClick={onQuickAdd} aria-label="Quick add">＋</button>{nav.slice(4).map((item) => <button className={base === item.id ? "active" : ""} onClick={() => go(item.id)} key={item.id}><span>{item.icon}</span>{item.label}</button>)}<button className={moreOpen || ["projects","notes","inbox","review","settings"].includes(base) ? "active" : ""} onClick={() => setMoreOpen((open) => !open)} aria-expanded={moreOpen}><span>•••</span>More</button></nav></main>;
}
