"use client";

import { useState } from "react";
import type { Project, Task } from "../types/workspace";
import { Modal } from "./Modal";

export function TaskEditor({ task, projects, onSave, onDelete, onDuplicate, onClose }: { task: Task; projects: Project[]; onSave: (patch: Partial<Task>) => void; onDelete: () => void; onDuplicate: () => void; onClose: () => void }) {
  const [draft, setDraft] = useState(task);
  const [tags, setTags] = useState(task.tags.join(", "));
  const save = () => { if (!draft.title.trim()) return; onSave({ ...draft, title: draft.title.trim(), tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean) }); onClose(); };
  return <Modal title="Edit task" onClose={onClose}><div className="editor-form"><label>Task<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label>Description<textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="Add helpful details…" /></label><div className="field-grid"><label>Project<select value={draft.projectId ?? ""} onChange={(event) => setDraft({ ...draft, projectId: event.target.value || null })}><option value="">No project</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><label>Priority<select value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value as Task["priority"] })}><option value="NONE">None</option><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option></select></label><label>Schedule<input type="date" value={draft.scheduledDate ?? ""} onChange={(event) => setDraft({ ...draft, scheduledDate: event.target.value || null })} /></label><label>Due<input type="date" value={draft.dueDate ?? ""} onChange={(event) => setDraft({ ...draft, dueDate: event.target.value || null })} /></label><label>Estimate<input type="number" min="5" step="5" value={draft.estimatedMinutes ?? ""} onChange={(event) => setDraft({ ...draft, estimatedMinutes: Number(event.target.value) || null })} placeholder="Minutes" /></label><label>Tags<input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="design, release" /></label></div><div className="dialog-actions split"><div><button className="button danger-quiet" onClick={() => { onDelete(); onClose(); }}>Delete</button><button className="button quiet" onClick={() => { onDuplicate(); onClose(); }}>Duplicate</button></div><div><button className="button quiet" onClick={onClose}>Cancel</button><button className="button primary" onClick={save}>Save task</button></div></div></div></Modal>;
}
